cognitive-complexity-threshold = 16
too-many-arguments-threshold = 5
single-char-binding-names-threshold = 1
too-many-lines-threshold = 42
array-size-threshold = 128000
allow-expect-in-tests = true
allow-unwrap-in-tests = true
